name: .NET Build and Test

on:
  push:
    branches:
      - master  # Використовуємо гілку master
  pull_request:
    branches:
      - master  # Використовуємо гілку master

jobs:
  build:
    runs-on: ubuntu-latest  # Ви можете використовувати інші платформи, наприклад, windows-latest чи macos-latest

    steps:
      # Крок 1: Checkout репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Крок 2: Налаштування .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'  # Вказуємо .NET 9.0

      # Крок 3: Відновлення залежностей
      - name: Restore dependencies
        run: dotnet restore

      # Крок 4: Публікація рішення
      - name: Build
        run: dotnet build --configuration Release

      # Крок 5: Запуск тестів
      - name: Run tests
        run: |
          dotnet test --configuration Release --no-build --verbosity normal
        continue-on-error: false  # Зупинити дію при помилці тестів

      # Крок 6: (Optional) Очищення після тестів або додаткові кроки
      - name: Clean up
        run: dotnet clean
